# Generated by Django 4.2 on 2025-10-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
