# Generated by Django 4.2 on 2025-10-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_message_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterField(
            model_name="message",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
