# Generated by Django 4.2 on 2025-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_room_options_alter_message_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
